export const INREASE_COUNTER = 'INREASE_COUNTER';
export const DECREASE_COUNTER = 'DECREASE_COUNTER';
export const ASYNC_INCREMENT = 'ASYNC_INCREMENT';
export const ASYNC_DECREMENT = 'ASYNC_DECREMENT';